hakuroukun:
    # Publish all joint states -----------------------------------
    joint_state_publisher:
        type: "joint_state_controller/JointStateController"
        publish_rate: 50

    # Position Controllers ---------------------------------------
    front_wheel_shaft_position_controller:
        type: velocity_controllers/JointVelocityController
        joint: rear_axis_center_to_front_wheel_shaft
        pid: {p: 1000.0, i: 0.01, d: 10.0}
    
    # Velocity Controllers ---------------------------------------
    rear_left_wheel_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rear_axis_center_to_rear_left_wheel
        pid: {p: 1000.0, i: 0.01, d: 10.0}
    rear_right_wheel_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rear_axis_center_to_rear_right_wheel
        pid: {p: 1000.0, i: 0.01, d: 10.0}

    # Effort Controllers ---------------------------------------
    # front_wheel_velocity_controller:
    #     type: effort_controllers/JointVelocityController
    #     joint: front_wheel_shaft_to_front_wheel
    #     pid: {p: 1000.0, i: 0.01, d: 10.0}